#!/usr/bin/env python
import os

# Zauważ, że wpisaliśmy tutaj Twoją dokładną nazwę folderu!
env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

library = env.SharedLibrary(
    "bin/dino{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)